# Generated by Django 4.0 on 2021-12-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.TextField(max_length=1000, verbose_name='Имя таблицы')),
                ('interface_name', models.TextField(max_length=1000, verbose_name='Пользовательское имя раздела')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('include', models.IntegerField(max_length=1000, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.TextField(max_length=1000, verbose_name='Номер раздела')),
                ('param_name', models.TextField(max_length=1000, verbose_name='Имя таблицы')),
                ('interface_name', models.TextField(max_length=1000, verbose_name='Пользовательское имя таблицы')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('include', models.IntegerField(max_length=1000, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Subsections_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.TextField(max_length=1000, verbose_name='Номер раздела')),
                ('subsection_id', models.TextField(max_length=1000, verbose_name='Номер подраздела')),
                ('html_form_data_type', models.TextField(max_length=1000, verbose_name='Тип данных HTML-формы для ввода записи')),
                ('sql_field_data_type', models.TextField(max_length=1000, verbose_name='Тип данных для поля таблицы БД')),
                ('html_descriptor', models.TextField(max_length=1000, verbose_name='Метка HTML-формы для ввода записи')),
                ('sql_field_name', models.TextField(max_length=1000, verbose_name='Имя поля таблицы БД')),
                ('required', models.TextField(max_length=1000, verbose_name='Обязательность заполнения')),
            ],
        ),
    ]
